/* The following code was generated by JFlex 1.4.2 on 3/15/24, 8:39 PM */

package edu.tsinghua.ss.thufv.specLang.parse;

import com.github.jhoenicke.javacup.runtime.*;
import java.math.BigInteger;
import java.util.*;


/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.4.2
 * on 3/15/24, 8:39 PM from the specification file
 * <tt>p4ltl.flex</tt>
 */
public class P4LTLLexer implements com.github.jhoenicke.javacup.runtime.Scanner {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;
  public static final int PREDICATE = 2;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0,  0,  1, 1
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\3\1\2\1\0\1\3\1\1\22\0\1\3\1\37\1\0"+
    "\1\5\2\0\1\33\1\0\1\20\1\21\1\0\1\47\1\40\1\50"+
    "\1\17\1\0\1\6\1\13\1\14\2\15\1\16\4\7\2\0\1\26"+
    "\1\35\1\27\2\0\1\22\5\10\4\4\1\44\4\4\1\23\1\4"+
    "\1\32\2\4\1\30\1\4\1\31\1\36\2\4\1\24\1\0\1\25"+
    "\1\0\1\4\1\0\1\55\1\10\1\10\1\43\1\45\1\54\2\4"+
    "\1\61\1\4\1\63\1\42\1\62\1\4\1\41\1\60\1\4\1\52"+
    "\1\56\1\51\1\53\1\11\1\57\1\12\1\46\1\4\1\0\1\34"+
    "\1\0\1\4\uff81\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\2\0\2\1\1\2\1\3\1\4\1\2\2\0\1\5"+
    "\1\6\1\7\3\0\1\10\1\11\2\12\1\2\2\12"+
    "\1\13\1\14\1\15\1\16\1\17\1\20\1\0\1\11"+
    "\1\21\3\2\1\22\1\23\4\2\1\24\1\25\1\26"+
    "\1\27\1\30\3\0\1\12\1\2\1\12\1\31\1\32"+
    "\1\33\1\34\10\2\1\35\1\36\4\0\1\12\1\2"+
    "\1\37\1\2\1\40\2\2\1\41\2\2\2\0\1\2"+
    "\1\42\1\43\3\2\4\0\1\44\1\45\1\46\1\2"+
    "\2\0\1\47\5\50";

  private static int [] zzUnpackAction() {
    int [] result = new int[104];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\64\0\150\0\234\0\320\0\234\0\234\0\u0104"+
    "\0\u0138\0\u016c\0\320\0\320\0\320\0\u01a0\0\u01d4\0\u0208"+
    "\0\320\0\234\0\u023c\0\u0270\0\u02a4\0\u02d8\0\u030c\0\234"+
    "\0\234\0\234\0\234\0\u0340\0\u0374\0\u03a8\0\u03dc\0\234"+
    "\0\u0410\0\u0444\0\u0478\0\234\0\234\0\u04ac\0\u04e0\0\u0514"+
    "\0\u0548\0\320\0\234\0\234\0\234\0\234\0\u057c\0\u05b0"+
    "\0\u05e4\0\u0618\0\u064c\0\u0680\0\234\0\234\0\u057c\0\234"+
    "\0\u06b4\0\u06e8\0\u071c\0\u0750\0\u0784\0\u07b8\0\u07ec\0\u0820"+
    "\0\234\0\u05b0\0\u0854\0\u0888\0\u08bc\0\u08f0\0\u0924\0\u0958"+
    "\0\320\0\u098c\0\320\0\u09c0\0\u09f4\0\320\0\u0a28\0\u0a5c"+
    "\0\u0a90\0\u0ac4\0\u0af8\0\320\0\320\0\u0b2c\0\u0b60\0\u0b94"+
    "\0\u0bc8\0\u0bfc\0\u0c30\0\u0c64\0\320\0\320\0\320\0\u0c98"+
    "\0\u0ccc\0\u0d00\0\320\0\234\0\u0d34\0\u0d68\0\u0d9c\0\u0dd0";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[104];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\0\1\3\2\4\1\5\3\0\3\5\5\0\1\6"+
    "\1\7\1\10\1\5\1\11\1\0\1\12\1\0\1\13"+
    "\1\14\1\15\1\16\1\17\1\20\1\21\1\22\1\0"+
    "\6\5\2\0\13\5\1\0\1\3\2\4\1\5\1\0"+
    "\1\23\1\24\1\5\1\25\1\5\1\26\1\27\2\24"+
    "\1\0\1\30\1\31\2\5\1\32\1\33\1\34\1\35"+
    "\3\5\1\16\1\17\1\36\1\5\1\37\1\40\1\41"+
    "\1\5\1\42\1\43\2\5\1\44\1\45\1\46\2\5"+
    "\1\47\1\50\3\5\1\51\2\5\2\0\1\4\151\0"+
    "\14\5\2\0\2\5\4\0\3\5\3\0\1\5\2\0"+
    "\6\5\2\0\13\5\4\0\14\5\2\0\1\5\1\52"+
    "\4\0\3\5\3\0\1\5\2\0\6\5\2\0\13\5"+
    "\25\0\1\53\65\0\1\54\67\0\1\55\64\0\1\56"+
    "\64\0\1\57\40\0\1\60\4\0\1\61\16\0\1\60"+
    "\33\0\2\62\3\0\4\62\1\61\50\0\14\5\2\0"+
    "\2\5\4\0\3\5\3\0\1\5\2\0\6\5\2\0"+
    "\4\5\1\63\6\5\6\0\2\24\3\0\4\24\1\61"+
    "\52\0\1\24\1\62\3\0\3\24\1\64\1\61\101\0"+
    "\1\65\63\0\1\66\63\0\1\67\63\0\1\70\32\0"+
    "\14\5\2\0\2\5\4\0\3\5\3\0\1\5\2\0"+
    "\1\5\1\71\4\5\2\0\13\5\4\0\14\5\2\0"+
    "\2\5\4\0\3\5\3\0\1\5\2\0\6\5\2\0"+
    "\1\5\1\72\11\5\4\0\14\5\2\0\2\5\4\0"+
    "\3\5\3\0\1\5\2\0\4\5\1\73\1\5\2\0"+
    "\13\5\4\0\14\5\2\0\2\5\4\0\3\5\3\0"+
    "\1\5\2\0\6\5\2\0\1\5\1\74\11\5\4\0"+
    "\14\5\2\0\2\5\4\0\3\5\3\0\1\5\2\0"+
    "\6\5\2\0\4\5\1\75\1\5\1\76\4\5\4\0"+
    "\14\5\2\0\2\5\4\0\3\5\3\0\1\5\2\0"+
    "\6\5\2\0\7\5\1\77\3\5\4\0\14\5\2\0"+
    "\2\5\4\0\3\5\3\0\1\5\2\0\6\5\2\0"+
    "\7\5\1\100\3\5\27\0\1\101\42\0\3\102\2\0"+
    "\4\102\3\0\1\102\20\0\1\102\1\0\1\102\6\0"+
    "\2\102\14\0\1\103\1\104\3\0\1\105\1\106\2\104"+
    "\53\0\2\107\3\0\4\107\1\61\50\0\14\5\2\0"+
    "\2\5\4\0\3\5\3\0\1\5\2\0\1\5\1\110"+
    "\4\5\2\0\13\5\6\0\1\62\1\107\3\0\4\62"+
    "\1\61\50\0\14\5\2\0\2\5\4\0\3\5\3\0"+
    "\1\5\2\0\2\5\1\111\3\5\2\0\13\5\4\0"+
    "\14\5\2\0\2\5\4\0\3\5\3\0\1\5\2\0"+
    "\1\112\5\5\2\0\13\5\4\0\14\5\2\0\2\5"+
    "\4\0\3\5\3\0\1\5\2\0\5\5\1\113\2\0"+
    "\13\5\4\0\14\5\2\0\2\5\4\0\3\5\3\0"+
    "\1\5\2\0\6\5\2\0\2\5\1\114\10\5\4\0"+
    "\14\5\2\0\2\5\4\0\3\5\3\0\1\5\2\0"+
    "\1\5\1\115\4\5\2\0\13\5\4\0\14\5\2\0"+
    "\2\5\4\0\3\5\3\0\1\5\2\0\2\5\1\116"+
    "\3\5\2\0\13\5\4\0\14\5\2\0\2\5\4\0"+
    "\3\5\3\0\1\5\2\0\6\5\2\0\7\5\1\117"+
    "\3\5\4\0\14\5\2\0\2\5\4\0\3\5\3\0"+
    "\1\5\2\0\6\5\2\0\11\5\1\120\1\5\17\0"+
    "\1\121\52\0\2\103\3\0\4\103\1\121\52\0\2\104"+
    "\3\0\4\104\1\121\52\0\1\104\1\103\3\0\3\104"+
    "\1\122\1\121\52\0\2\107\3\0\4\107\51\0\14\5"+
    "\2\0\2\5\4\0\3\5\3\0\1\5\2\0\6\5"+
    "\2\0\10\5\1\123\2\5\4\0\14\5\2\0\2\5"+
    "\4\0\3\5\3\0\1\5\2\0\6\5\2\0\7\5"+
    "\1\124\3\5\4\0\14\5\2\0\2\5\4\0\3\5"+
    "\3\0\1\5\2\0\4\5\1\125\1\5\2\0\13\5"+
    "\4\0\14\5\2\0\2\5\4\0\3\5\3\0\1\5"+
    "\2\0\6\5\2\0\5\5\1\126\5\5\4\0\14\5"+
    "\2\0\2\5\4\0\3\5\3\0\1\5\2\0\1\5"+
    "\1\127\4\5\2\0\13\5\4\0\14\5\2\0\2\5"+
    "\4\0\3\5\3\0\1\5\2\0\6\5\2\0\4\5"+
    "\1\130\6\5\6\0\1\131\1\132\3\0\1\133\1\134"+
    "\2\132\53\0\1\103\4\0\4\103\1\121\50\0\14\5"+
    "\2\0\2\5\4\0\3\5\3\0\1\5\2\0\2\5"+
    "\1\135\3\5\2\0\13\5\4\0\14\5\2\0\2\5"+
    "\4\0\3\5\3\0\1\5\2\0\4\5\1\136\1\5"+
    "\2\0\13\5\4\0\14\5\2\0\2\5\4\0\3\5"+
    "\3\0\1\5\2\0\5\5\1\137\2\0\13\5\4\0"+
    "\14\5\2\0\2\5\4\0\3\5\3\0\1\5\2\0"+
    "\6\5\2\0\5\5\1\140\5\5\17\0\1\141\52\0"+
    "\2\131\3\0\4\131\1\141\52\0\2\132\3\0\4\132"+
    "\1\141\52\0\1\132\1\131\3\0\3\132\1\142\1\141"+
    "\50\0\14\5\2\0\2\5\4\0\3\5\3\0\1\5"+
    "\2\0\6\5\2\0\12\5\1\143\6\0\1\144\1\145"+
    "\3\0\1\146\1\147\2\145\53\0\1\131\4\0\4\131"+
    "\1\141\52\0\2\144\3\0\4\144\53\0\2\145\3\0"+
    "\4\145\53\0\1\145\1\144\3\0\3\145\1\150\53\0"+
    "\1\144\4\0\4\144\45\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[3588];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unkown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\2\0\1\1\1\11\1\1\2\11\1\1\2\0\3\1"+
    "\3\0\1\1\1\11\5\1\4\11\2\1\1\0\1\1"+
    "\1\11\3\1\2\11\5\1\4\11\3\0\3\1\2\11"+
    "\1\1\1\11\10\1\1\11\1\1\4\0\12\1\2\0"+
    "\6\1\4\0\4\1\2\0\1\1\1\11\4\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[104];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /* user code: */
  private Symbol symbol(int type) {
    return new Symbol(type, yyline, yycolumn);
  }
  private Symbol symbol(int type, Object value) {
    return new Symbol(type, yyline, yycolumn, value);
  }
	private Symbol symbol(int type, String value) {
    return new Symbol(type, yyline, yycolumn, value);
  }
  
      private Symbol symbol(int type, int value) {
    return new Symbol(type, yyline, yycolumn, value);
  }
  private void echoToken(String text)
  {
  	 // System.out.println("Token: " + text);
  }
  
  int parens = 0;


  /**
   * Creates a new scanner
   * There is also a java.io.InputStream version of this constructor.
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public P4LTLLexer(java.io.Reader in) {
    this.zzReader = in;
  }

  /**
   * Creates a new scanner.
   * There is also java.io.Reader version of this constructor.
   *
   * @param   in  the java.io.Inputstream to read input from.
   */
  public P4LTLLexer(java.io.InputStream in) {
    this(new java.io.InputStreamReader(in));
  }

  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x10000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 166) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzCurrentPos*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
    }

    /* finally: fill the buffer with new input */
    int numRead = zzReader.read(zzBuffer, zzEndRead,
                                            zzBuffer.length-zzEndRead);

    if (numRead > 0) {
      zzEndRead+= numRead;
      return false;
    }
    // unlikely but not impossible: read 0 characters, but not at end of stream    
    if (numRead == 0) {
      int c = zzReader.read();
      if (c == -1) {
        return true;
      } else {
        zzBuffer[zzEndRead++] = (char) c;
        return false;
      }     
    }

	// numRead < 0
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public com.github.jhoenicke.javacup.runtime.Symbol next_token() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      for (zzCurrentPosL = zzStartRead; zzCurrentPosL < zzMarkedPosL;
                                                             zzCurrentPosL++) {
        switch (zzBufferL[zzCurrentPosL]) {
        case '\u000B':
        case '\u000C':
        case '\u0085':
        case '\u2028':
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn++;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL)
            zzInput = zzBufferL[zzCurrentPosL++];
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = zzBufferL[zzCurrentPosL++];
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          int zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
        case 1: 
          { /* ignore */
          }
        case 41: break;
        case 10: 
          { echoToken(yytext()); return symbol(P4LTLSymbols.INT, new BigInteger(yytext()));
          }
        case 42: break;
        case 33: 
          { echoToken(yytext()); return symbol(P4LTLSymbols.FWD);
          }
        case 43: break;
        case 39: 
          { echoToken(yytext()); return symbol(P4LTLSymbols.IPMASK);
          }
        case 44: break;
        case 31: 
          { echoToken(yytext()); return symbol(P4LTLSymbols.OLD);
          }
        case 45: break;
        case 38: 
          { echoToken(yytext()); return symbol(P4LTLSymbols.APPLY);
          }
        case 46: break;
        case 9: 
          { echoToken(yytext()); return symbol(P4LTLSymbols.NEG);
          }
        case 47: break;
        case 24: 
          { echoToken(yytext()); return symbol(P4LTLSymbols.OR);
          }
        case 48: break;
        case 21: 
          { echoToken(yytext()); return symbol(P4LTLSymbols.ALWAYS);
          }
        case 49: break;
        case 27: 
          { echoToken(yytext()); return symbol(P4LTLSymbols.EQ);
          }
        case 50: break;
        case 30: 
          { echoToken(yytext()); return symbol(P4LTLSymbols.INT, new BigInteger(yytext().substring(2), 16));
          }
        case 51: break;
        case 5: 
          { echoToken(yytext()); return symbol(P4LTLSymbols.UNTIL);
          }
        case 52: break;
        case 22: 
          { echoToken(yytext()); return symbol(P4LTLSymbols.EVENTUALLY);
          }
        case 53: break;
        case 2: 
          { echoToken(yytext()); return symbol(P4LTLSymbols.NAME, yytext());
          }
        case 54: break;
        case 19: 
          { echoToken(yytext()); return symbol(P4LTLSymbols.MINUS);
          }
        case 55: break;
        case 3: 
          { echoToken(yytext()); return symbol(P4LTLSymbols.LPAR);
          }
        case 56: break;
        case 13: 
          { echoToken(yytext()); return symbol(P4LTLSymbols.LBRACKET);
          }
        case 57: break;
        case 25: 
          { echoToken(yytext()); return symbol(P4LTLSymbols.LEQ);
          }
        case 58: break;
        case 4: 
          { echoToken(yytext()); return symbol(P4LTLSymbols.RPAR);
          }
        case 59: break;
        case 29: 
          { echoToken(yytext()); return symbol(P4LTLSymbols.IMPLIES);
          }
        case 60: break;
        case 17: 
          { echoToken(yytext()); return symbol(P4LTLSymbols.COMMA);
          }
        case 61: break;
        case 12: 
          { echoToken(yytext()); parens--; if(parens == 0) { yybegin(YYINITIAL); } return symbol(P4LTLSymbols.RPAR);
          }
        case 62: break;
        case 16: 
          { echoToken(yytext()); return symbol(P4LTLSymbols.GT);
          }
        case 63: break;
        case 37: 
          { echoToken(yytext()); return symbol(P4LTLSymbols.FALSE);
          }
        case 64: break;
        case 15: 
          { echoToken(yytext()); return symbol(P4LTLSymbols.LT);
          }
        case 65: break;
        case 40: 
          { echoToken(yytext()); return symbol(P4LTLSymbols.IP, yytext());
          }
        case 66: break;
        case 36: 
          { echoToken(yytext()); return symbol(P4LTLSymbols.VALID);
          }
        case 67: break;
        case 7: 
          { echoToken(yytext()); return symbol(P4LTLSymbols.RELEASE);
          }
        case 68: break;
        case 8: 
          { echoToken(yytext()); return symbol(P4LTLSymbols.NEXT);
          }
        case 69: break;
        case 18: 
          { echoToken(yytext()); return symbol(P4LTLSymbols.PLUS);
          }
        case 70: break;
        case 23: 
          { echoToken(yytext()); return symbol(P4LTLSymbols.AND);
          }
        case 71: break;
        case 34: 
          { echoToken(yytext()); return symbol(P4LTLSymbols.DROP);
          }
        case 72: break;
        case 14: 
          { echoToken(yytext()); return symbol(P4LTLSymbols.RBRACKET);
          }
        case 73: break;
        case 35: 
          { echoToken(yytext()); return symbol(P4LTLSymbols.TRUE);
          }
        case 74: break;
        case 6: 
          { echoToken(yytext()); return symbol(P4LTLSymbols.WEAKUNTIL);
          }
        case 75: break;
        case 32: 
          { echoToken(yytext()); return symbol(P4LTLSymbols.KEY);
          }
        case 76: break;
        case 11: 
          { echoToken(yytext()); parens++; return symbol(P4LTLSymbols.LPAR);
          }
        case 77: break;
        case 26: 
          { echoToken(yytext()); return symbol(P4LTLSymbols.GEQ);
          }
        case 78: break;
        case 20: 
          { echoToken(yytext()); yybegin(PREDICATE); return symbol(P4LTLSymbols.AP);
          }
        case 79: break;
        case 28: 
          { echoToken(yytext()); return symbol(P4LTLSymbols.NEQ);
          }
        case 80: break;
        default: 
          if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
            zzAtEOF = true;
              {
                echoToken(yytext()); return symbol(P4LTLSymbols.EOF);
              }
          } 
          else {
            zzScanError(ZZ_NO_MATCH);
          }
      }
    }
  }


}
