
//----------------------------------------------------
// The following code was generated by jh-javacup-1.2 20210807
// Mon Oct 17 12:15:40 CST 2022
//----------------------------------------------------

package edu.tsinghua.ss.thufv.specLang.parse;

/** CUP generated class containing symbol constants. */
public class P4LTLSymbols {
  /* terminals */
  public static final int error = 0;
  public static final int EOF = 1;
  public static final int AP = 2;
  public static final int COMMA = 3;
  public static final int LPAR = 4;
  public static final int RPAR = 5;
  public static final int LBRACKET = 6;
  public static final int RBRACKET = 7;
  public static final int APPLY = 8;
  public static final int DROP = 9;
  public static final int IPMASK = 10;
  public static final int ALWAYS = 11;
  public static final int EVENTUALLY = 12;
  public static final int UNTIL = 13;
  public static final int WEAKUNTIL = 14;
  public static final int RELEASE = 15;
  public static final int AND = 16;
  public static final int OR = 17;
  public static final int IMPLIES = 18;
  public static final int NEXT = 19;
  public static final int NEG = 20;
  public static final int EQ = 21;
  public static final int NEQ = 22;
  public static final int TRUE = 23;
  public static final int FALSE = 24;
  public static final int OLD = 25;
  public static final int KEY = 26;
  public static final int PLUS = 27;
  public static final int MINUS = 28;
  public static final int FWD = 29;
  public static final int VALID = 30;
  public static final int GT = 31;
  public static final int GEQ = 32;
  public static final int LT = 33;
  public static final int LEQ = 34;
  public static final int NAME = 35;
  public static final int IP = 36;
  public static final int INT = 37;
}

