/* BitvecLiteral -- Automatically generated by TreeBuilder (2022-06-30T15:29Z) */

package ast;

import de.uni_freiburg.informatik.ultimate.ltl2aut.ast.AstNode;
import de.uni_freiburg.informatik.ultimate.ltl2aut.ast.Name;

public class BitVecNode extends AstNode {
    /**
     * The number of bits in this bitvector.
     * -1 means `unset`.
     */
    int length = -1;

    public int getLength() {
        return length;
    }
    
	public static int getBitVecNodeLength(AstNode node)
	{
		if(node instanceof BitVecNode)
		{
			return ((BitVecNode) node).length;
		}
		else if(node instanceof Name)
		{
			return -1;
		}
		else
		{
			throw new IllegalArgumentException("Unexpected node for bit vec operator: " + node.toString());
		}
	}
}
